### ISSUE TITLE
Pelagus Wallet never initialized after signup flow

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#150]
Discord Discussion Link
No response

What browsers are you seeing the problem on?
Chrome

What were you trying to do?
Create a new wallet with a new seed in Pelagus.

What did not work?
Upon finishing the initial seed verification, the Pelagus site lands on a page that says "Account Added to Pelagus". When you reach this page, clicking on the extension immediately closes it and returns you to the same web page. The page looks like this:

![Image](https://github.com/PelagusWallet/pelagus-extension/assets/41161464/f56d2be5-838d-4bd0-be25-0d182c665216)

The issue seems to be non-deterministic as this flow works some of the time, but not all.

The correct flow lands you on a page that looks like this:

![Image](https://github.com/PelagusWallet/pelagus-extension/assets/41161464/68ae55ef-371f-4e77-bcea-5031f36a3b41)

Version
None

Relevant log output
logger.ts:210 Async thunk failed Error: KeyringService must be unlocked.
    at KeyringService.requireUnlocked (index.ts:286:13)
    at KeyringService.persistKeyrings (index.ts:717:10)
    at KeyringService.importKeyring (index.ts:353:16)
    at main.ts:1498:35
    at index.js:306:13
    at Array.map (<anonymous>)
    at Emittery.emit (index.js:304:23)
    at async keyrings.ts:56:65
    at async utils.ts:129:9
logEvent@logger.ts:210

**Comment by mibuono** [comment]
This issue elaborates on the issue noted in https://github.com/PelagusWallet/pelagus-extension/issues/143 by @maxbibeau.

It should be noted that during a successful setup, there is a console log that notes that the KeyringService is unlocked. When the setup is unsuccessful, there is a console error that notes the KeyringService must be unlocked.

**Comment by ArtemBurakov** [comment]
I have not been able to reproduce this problem on my machine. Tried creating the first wallet, adding another wallet, etc. but everything works as it should. It also works as expected if the wallet is not used for a while.

Can you please provide the exact steps to reproduce this bug.

**Comment by mibuono** [comment]
This issue is very tricky - it happens intermittently and is difficult to reproduce.

**Comment by mibuono** [comment]
It should be noted that during a successful setup, there is a console log that notes that the KeyringService is unlocked. When the setup is unsuccessful, there is a console error that notes the KeyringService must be unlocked. (from Judi)

**Comment by ArtemBurakov** [comment]
the **Account added to Pelagus** page is displayed when you create another wallet after having already created one, and the **Welcome to Pelagus** page is displayed when you have created your first wallet

so I don't really understand the flow:
1) you tried to create your first wallet (and since there was a problem with the service) it redirected you to another page "Account added to Pelagus", which should not be displayed when creating the first wallet? (and should have shown "Welcome to Palagus")

2) or having an existing wallet, you created another wallet and you are correctly redirected to the "Account added to Pelagus" page, but when you click on the wallet image (due to a service problem) you do not see the wallet menu and remain on the "Account, added to Pelagus”?

**Comment by ArtemBurakov** [comment]
I'm a bit confused by the **Welcome to Pelagus** page you expect to see. You may have been correctly redirected to the **Account added to Pelagus** page, but due to an error in the service or smt else, you cannot open the wallet and it immediately closes.
