### ISSUE TITLE
[Pelagus] -Wallet fails to connect to a dapp after leaving the webpage open for a while

### ISSUE THREAD

**Issue by mibuono** [PelagusWallet/pelagus-extension#155]
The provider bridge port is disconnecting causing any interaction between the dapp and wallet to fail.

![Image](https://github.com/PelagusWallet/pelagus-extension/assets/41161464/225a5607-0c01-49e1-8d02-b43e8656a68f)

**Comment by rileystephens28** [comment]
@booleksandra after speaking with the team, I have realized that this issue is happening much more frequently than I thought at first. For this reason I am increasing the priority from P2 to P0. @ArtemBurakov please work on this ticket after you complete #167 and #148. 

I have confirmed that this issue occurs when a user navigates to a dapp then:
1. waits for a while before attempting to connect Pelagus
2. immediately connects Pelagus then waiting for a while before interacting with the dapp in another way that requires use of Pelagus

**Comment by booleksandra** [comment]
> [@booleksandra](https://github.com/booleksandra) after speaking with the team, I have realized that this issue is happening much more frequently than I thought at first. For this reason I am increasing the priority from P2 to P0. [@ArtemBurakov](https://github.com/ArtemBurakov) please work on this ticket after you complete [#167](https://github.com/PelagusWallet/pelagus-extension/issues/167) and [#148](https://github.com/PelagusWallet/pelagus-extension/issues/148).
> 
> I have confirmed that this issue occurs when a user navigates to a dapp then:
> 
> 1. waits for a while before attempting to connect Pelagus
> 2. immediately connects Pelagus then waiting for a while before interacting with the dapp in another way that requires use of Pelagus

Updates for the steps to reproduce:
**Test environment**:
Browser - Google Chrome, Version 123.0.6312.87

**The fastest reproducing is**:
1. Open the [site](https://quaimark.com/) (do not connected wallet)
2. Wait for 5-20 minutes (open another tab, app, just do smt else)
3. Connect the wallet. 
4. Check the connection between the wallet and Dapp. If wallets connects after this time - everything is fine
**OPTIONAL**: Check the connection between the wallet and Dapp in the console. Each 30 seconds will be emitted health check log. If port is down it will be reconnected.
