### ISSUE TITLE
Error occurs when importing seed phrase

### ISSUE THREAD

**Issue by rileystephens28** [PelagusWallet/pelagus-extension#195]
Test environment:
Browser - Google Chrome, Version 123.0.6312.107

Steps to reproduce :

1.Download the [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar)
2. Click on [Import from Recovery Phrase].
3. Fill in the password fields
4. Input recovery phrase
5. Click [Import Account]

Expected result:
User is redirected to success page.

Actual result:
After clicking on the [Import Account], the page hangs

Console

![Image](https://github.com/PelagusWallet/pelagus-extension/assets/24363438/b98022c4-2b3a-4001-aa5d-7fdc4778fb3d)

**Comment by rileystephens28** [comment]
I am not completely sure this was using an up to date unpacked version of the extension. I ran `yarn dev` and reloaded the unpacked extension and have not been able to reproduce since. @booleksandra can you please confirm if you are able to reproduce this issue?

**Comment by booleksandra** [comment]
> I am not completely sure this was using an up to date unpacked version of the extension. I ran `yarn dev` and reloaded the unpacked extension and have not been able to reproduce since. [@booleksandra](https://github.com/booleksandra) can you please confirm if you are able to reproduce this issue?

Yes, I also had this bug appear once. Now I am looking for the best way to reproduce it. If I find the steps that will reproduce it 5/5, I will add it to the comments to this task

**Comment by booleksandra** [comment]
This bug is reproduced all the time by following these steps :

1. Download the [extension](https://chromewebstore.google.com/detail/pelagus/gaegollnpijhedifeeeepdoffkgfcmbc?hl=uk&utm_source=ext_sidebar)
2. Сlick on [Use existing wallet]
3. Click on [Import from Recovery Phrase].
4. Fill in the password fields
5. Click on [Anchors Away!]
6. Wait 2+ minutes before filling in the field
7. Fill in "Input recovery phrase" field
8. Click [Import Account]
